# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'RNFilePicker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFilePicker
pod 'FPPicker', '~> 5.1.1'
  target 'RNFilePicker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNFilePickerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNFilePicker-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFilePicker-tvOS


end
